## Recorrer una API paginada y almacenar todos los datos en un solo dataframe

In [121]:
import requests
import json
import pandas as pd
import time
from multiprocessing import Pool as ThreadPool
from multiprocessing import cpu_count

offset=0 #Parametros iniciales
limit=1000 # Parametrod iniciales
lista_offset = [0,1000,2000,3000]

def api_function(lista_offset):
  print(lista_offset)
  lista=[]

  for offset in lista_offset:
    print(offset)
    url="http://jsonplaceholder.typicode.com/photos?_start={}&_limit={}".format(offset,limit)
    result = requests.get(url)
    data_extracted=result.json()
    lista.append(pd.json_normalize(data_extracted))
  return lista

In [122]:
s = time.time()
pool = ThreadPool(4)
results = pool.map(api_function, [lista_offset])
df = pd.concat(results[0])
df

[0, 1000, 2000, 3000]
0
1000
2000
3000

,albumId,id,title,url,thumbnailUrl
0,1,1,accusamus beatae ad facilis cum similique qui ...,https://via.placeholder.com/600/92c952,https://via.placeholder.com/150/92c952
1,1,2,reprehenderit est deserunt velit ipsam,https://via.placeholder.com/600/771796,https://via.placeholder.com/150/771796
2,1,3,officia porro iure quia iusto qui ipsa ut modi,https://via.placeholder.com/600/24f355,https://via.placeholder.com/150/24f355
3,1,4,culpa odio esse rerum omnis laboriosam volupta...,https://via.placeholder.com/600/d32776,https://via.placeholder.com/150/d32776
4,1,5,natus nisi omnis corporis facere molestiae rer...,https://via.placeholder.com/600/f66b97,https://via.placeholder.com/150/f66b97
...,...,...,...,...,...
995,80,3996,iste explicabo nemo molestiae,https://via.placeholder.com/600/1054f2,https://via.placeholder.com/150/1054f2
996,80,3997,quisquam quam eos,https://via.placeholder.com/600/913d78,https://via.placeholder.com/150/913d78
997,80,3998,occaecati accusamus suscipit facilis non ab eu...,https://via.placeholder.com/600/d7686f,https://via.placeholder.com/150/d7686f
998,80,3999,earum quisquam dolores ipsa voluptatibus neces...,https://via.placeholder.com/600/66b81b,https://via.placeholder.com/150/66b81b
999,80,4000,neque iure sunt explicabo ab,https://via.placeholder.com/600/8cf664,https://via.placeholder.com/150/8cf664

In [120]:
df.groupby('id').count()

      albumId  title  url  thumbnailUrl
id
1           1      1    1             1
2           1      1    1             1
3           1      1    1             1
4           1      1    1             1
5           1      1    1             1
...       ...    ...  ...           ...
2496        1      1    1             1
2497        1      1    1             1
2498        1      1    1             1
2499        1      1    1             1
2500        1      1    1             1

[2500 rows x 4 columns]